### ISSUE TITLE
Appveyor not working

### ISSUE THREAD

**Issue by wkschwartz** [wkschwartz/shutdown#20]
The first job of a build hangs indefinitely either at the install phase, or, after running the tests and they fail, with the message
```
FAILED (failures=1, skipped=1)
Terminate batch job (Y/N)? 
```

For now I've turned off reading `appveyor.yml` on Appveyor's GUI/website. All the tests pass on my own Windows 7 machine running Python 3.7.

**Comment by wkschwartz** [comment]
The YAML code I've been trying is
```yaml
version: 1.0.{build}
environment:
  matrix:
  - PYTHON: C:\Python35
  - PYTHON: C:\Python35-x64
  - PYTHON: C:\Python36-x64
  - PYTHON: C:\Python37-x64
install:
- cmd: '%PYTHON%\python.exe setup.py install'
build: off
test_script:
- ps: >-
    &$env:PYTHON\python -m unittest discover tests
    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
```

I deleted the branch I was working on since it was broken anyway. Come back to this later.
